apiVersion: 1
datasources:
- name: Mimir
  type: prometheus
  access: proxy
  uid: mimir
  orgID: 1
  url: http://query-frontend:8007/prometheus
  jsonData:
    prometheusType: Mimir
    exemplarTraceIdDestinations:
    - name: traceID
      datasourceUid: jaeger
- name: Jaeger
  type: jaeger
  access: proxy
  uid: jaeger
  orgID: 1
  url: http://jaeger:16686/
- name: Mimir Orig
  type: prometheus
  access: proxy
  uid: mimirorig
  orgID: 1
  url: http://querier:8004/prometheus
- name: Prometheus
  type: prometheus
  access: proxy
  uid: prometheus
  orgID: 1
  url: http://prometheus:9090